# Generated by Django 3.1.1 on 2020-09-17 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200917_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instruments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=['guitar'], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='like_music',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=['pop'], size=None),
            preserve_default=False,
        ),
    ]
