# Generated by Django 3.1.1 on 2020-09-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200917_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instruments',
            field=models.CharField(choices=[('Guitar', 'Guitar'), ('Drums', 'Drums'), ('Piano', 'Piano'), ('Violin', 'Violin'), ('Saxophone', 'Saxophone'), ('Keyboard', 'Keyboard'), ('Flute', 'Flute'), ('Tabla', 'Tabla'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='like_music',
            field=models.CharField(choices=[('Pop Music', 'Pop Music'), ('Rock Music', 'Rock Music'), ('Folk Music', 'Folk Music'), ('Jazz Music', 'Jazz Music'), ('Blues Music', 'Blues Music'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
